version: "3"
services:
  eureka-server:
    image: eureka-server:1.0
    build: eureka-server/
    container_name: eureka-server
    ports:
      - 8761:8761

  api-gateway:
    image: api-gateway:1.0
    build: api-gateway/
    container_name: api-gateway
    ports:
      - 8080:8080
    links:
      - eureka-server
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/


  credwizmysqldb:
    image: mysql:latest
    container_name: "credwizmysqldb"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306

  product-webapp:
    build: product-webapp/
    image: product-webapp
    restart: always
    container_name: product-webapp
    ports:
      - 3000:3000
    links:
      - eureka-server
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    depends_on:
      - api-gateway

  user-service:
    image: user-service
    build: user-service/
    container_name: user-service
    restart: always
    ports:
      - 8090:8090
    links:
      - eureka-server
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    depends_on:
      - credwizmysqldb
      - api-gateway
  wallet-service:
    image: wallet-service
    build: wallet-service/
    container_name: wallet-service
    restart: always
    ports:
      - 9092:9092
    links:
      - eureka-server
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    depends_on:
      - credwizmysqldb
      - api-gateway
