eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true


server:
  port: 9090

spring:
  application:
    name: api-gateway

  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:

        - id: USER-SERVICE
          uri: http://user-service:8090/
          predicates:
            - Path=/user/**

#  cloud:
#    gateway:
#      routes:
#      - id: USER-SERVICE
#        uri: http://localhost:8090
#        predicates:
#          - Path=/user/**
#      - id: WALLET-SERVICE
#        uri: http://localhost:9092
#        predicates:
#          - Path=/wallet/**