eureka:
  client:
    service-url:
       defaultZone: http://eureka-server:8761/eureka
#      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true


server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    compatibility-verifier:
      enabled: false
    gateway:

      routes:
        - id: USER-SERVICE
          uri: http://user-service:8090
#          uri: http://localhost:8090
          predicates:
            - Path=/user/**
        - id: WALLET-SERVICE
          uri: http://wallet-service:9092
#          uri: http://localhost:9092
          predicates:
            - Path=/wallet/**
        - id: product-webapp
          uri: http://product-webapp:3000
          predicates:
            - Path=/product-webapp/**

      global-cors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
        add-to-simple-url-handler-mapping: true
  main:
    web-application-type: reactive



#  cloud:
#    gateway:
#      routes:
#      - id: USER-SERVICE
#        uri: http://user-service:8090
#        uri: http://localhost:8090
#        predicates:
#          - Path=/user/**
#      - id: WALLET-SERVICE
#        uri: http://wallet-service:9092
#        uri: http://localhost:9092
#        predicates:
#          - Path=/wallet/**