##eureka:
##  client:
##    service-url:
##       defaultZone: http://eureka-server:8761/eureka
###      defaultZone: http://localhost:8761/eureka
##    register-with-eureka: true
##    fetch-registry: true
##
##
##server:
##  port: 5005
##
##spring:
##  application:
##    name: api-gateway
##
##  cloud:
##    compatibility-verifier:
##      enabled: false
##    gateway:
##
##
##      global-cors:
##        corsConfigurations:
##          '[/**]':
##            allowedOrigins: "*"
##            allowedMethods: "*"
##            allowedHeaders: "*"
##            exposedHeaders: "*"
##        add-to-simple-url-handler-mapping: true
##  main:
##    web-application-type: reactive
##
##
##
###  cloud:
###    gateway:
###      routes:
###      - id: USER-SERVICE
###        uri: http://user-service:8090
###        uri: http://localhost:8090
###        predicates:
###          - Path=/user/**
###      - id: WALLET-SERVICE
###        uri: http://wallet-service:9092
###        uri: http://localhost:9092
###        predicates:
###          - Path=/wallet/**
#
#  Mohit Sharma1:35 PM
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true
#
#server:
#  port: 8080
#
#
#
#spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      global-cors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedHeaders:
#              - Content-Type
#            allowedMethods: "*"
#        add-to-simple-url-handler-mapping: true
#  main:
#    w
#  bct-fyva-pyo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 5005



spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      global-cors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - Content-Type
            allowedMethods: "*"
        add-to-simple-url-handler-mapping: true
  main:
    web-application-type: reactive
  application:
    name: "API-GATEWAY"